### ISSUE TITLE
Naves duplicadas

### ISSUE THREAD

**Issue by dogo** [djogopatrao/xwing_dial#2]
Essas naves estão duplicadas: 

**Galactic Republic & Rebel Alliance**
arc-170-starfighter.json
tie-ln-fighter.json

**Scum and Villainy & Rebel Alliance**
btl-a4-y-wing.json
hwk-290-light-freighter.json
z-95-af4-headhunter.json

Se isso estiver correto, acredito que podemos usar o mesmo json e criar um campo novo:

`"faction_code": ["SV", "RA"]`

Seria um array de opções da mesma nave

Sugestão de codes:

**RA** // Rebel Alliance
**GE** // Galactic Empire.   
**SV** // Scum and Villainy.     
**FO** // First Order.   
**GR** // Galactic Republic.   
**RE** // Resistance.   
**SA** // Separatist Alliance.

**Comment by dogo** [comment]
Humm percebi que os pilotos são diferentes no arquivo, já temos uma api para fazer o request destes jsons? Seria melhor pro front não ter isso dentro da aplicação e sim fazer um request, ai resolveríamos o problema de arquivos duplicados mas diferentes

**Comment by dogo** [comment]
Os jsons não deveriam ser separados? 
Tipo faço um `get` de todas as naves da `Rebel Alliance` vem todas as naves, sem piloto algum

Depois faço um `get` para todos os pilotos da `Rebel Alliance` que podem usar essa nave.

Assim, podemos separar bem as responsabilidades dos endpoints e os jsons não ficam tao amarrados

**Comment by djogopatrao** [comment]
a idéia do app web era poder ser hospedado no github.io, dessa forma preparamos os arquivos json com toda informação necessária para evitar a necessidade de um servidor, como comentado no #3.

**Comment by dogo** [comment]
Okay! :D
