### ISSUE TITLE
Criar uma API publica

### ISSUE THREAD

**Issue by dogo** [djogopatrao/xwing_dial#3]
Todas as informações estão sendo acessadas localmente isso é ruim para o front mobile, que depende de compilação e publicação na loja (Apple e Google).

Toda vez que precisamos atualizar/arrumar um JSON teríamos que compilar uma versão nova e mandar pra a loja, sendo que nem todo usuário faz atualização de app. Seria bom a gente ter uma API que envia esses dados algo como:

**Base url:**
`https://xwing-api.com/`

**Endpoints:**
`/api/public/starships/<faction_code>` -> Retorna todas as naves daquela facção
`/api/public/<faction_code>/pilots/<starship>` -> Retorna todas os pilotos daquela nave, levando em conta a facção

**Comment by djogopatrao** [comment]
Atualmente a aplicação tem uma instância em https://djogopatrao.github.com/xwing_dial

Os arquivos json podem ser acessados atraves do url https://djogopatrao.github.io/xwing_dial/data/data.json

Ao invés de implementar uma API (que exigiria um servidor de backend que hoje não tenho), acha viável o App recuperar o conteúdo deste arquivo deste URL sempre que for aberto?

**Comment by dogo** [comment]
Posso fazer isso sim, funciona. Mas seria legal num futuro termos um server
